import { formatReportDayLabel } from "@/lib/reportCalendar";
import { formatMealReportLine, formatWorkoutDuration, reportFileName, reportShareTitle, type UserReport } from "@/lib/userReport";
import { File } from "expo-file-system";
import * as Print from "expo-print";
import * as Sharing from "expo-sharing";

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function listSection(title: string, rows: string[], emptyText: string): string {
  const body =
    rows.length > 0
      ? `<ul>${rows.map((row) => `<li>${escapeHtml(row)}</li>`).join("")}</ul>`
      : `<p class="muted">${escapeHtml(emptyText)}</p>`;
  return `<section><h2>${escapeHtml(title)}</h2>${body}</section>`;
}

export function buildUserReportHtml(report: UserReport): string {
  const workoutRows = report.workouts.map(
    (item) =>
      `${item.title} — ${item.burnedKcal} kcal burned (${formatWorkoutDuration(item.durationMin)})`
  );
  const mealRows = report.meals.map((item) => formatMealReportLine(item));
  const waterRows =
    report.waterLogs.length > 0
      ? report.waterLogs.map((item) => `${item.amountMl} ml`)
      : report.waterMl > 0
        ? [`${report.waterMl} ml total`]
        : [];
  const weightRows = report.weightEntries.map(
    (item) => `${formatReportDayLabel(item.dayKey)} — ${item.weightKg.toFixed(1)} kg`
  );
  const stepRows =
    report.period === "weekly"
      ? report.stepsByDay
          .filter((row) => row.steps > 0)
          .map((row) => `${formatReportDayLabel(row.dayKey)} — ${row.steps.toLocaleString()} steps`)
      : [`${report.steps.toLocaleString()} steps`];
  const achievementRows = report.achievements.map(
    (item) => `${item.title} — ${item.description}`
  );
  const isWeekly = report.period === "weekly";
  const summaryLabel = (daily: string, weekly: string) => (isWeekly ? weekly : daily);

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; color: #0f172a; padding: 28px; font-size: 13px; line-height: 1.5; }
    h1 { font-size: 24px; margin: 0 0 4px; color: #14532d; }
    .subtitle { color: #64748b; margin: 0 0 20px; font-size: 14px; }
    .summary { display: grid; grid-template-columns: 1fr 1fr; gap: 10px; margin-bottom: 22px; }
    .card { border: 1px solid #d1fae5; background: #f0fdf4; border-radius: 12px; padding: 12px; }
    .label { font-size: 11px; text-transform: uppercase; letter-spacing: 0.08em; color: #64748b; }
    .value { font-size: 18px; font-weight: 700; color: #166534; margin-top: 4px; }
    section { margin-bottom: 18px; page-break-inside: avoid; }
    h2 { font-size: 15px; margin: 0 0 8px; color: #14532d; border-bottom: 1px solid #e2e8f0; padding-bottom: 4px; }
    ul { margin: 0; padding-left: 18px; }
    li { margin-bottom: 4px; }
    .muted { color: #94a3b8; font-style: italic; }
    .footer { margin-top: 24px; font-size: 11px; color: #94a3b8; text-align: center; }
  </style>
</head>
<body>
  <h1>${escapeHtml(report.userName)}</h1>
  <p class="subtitle">${escapeHtml(report.subtitle)} · ${escapeHtml(report.title)}</p>

  <div class="summary">
    <div class="card"><div class="label">${summaryLabel("Workout burned", "Total burned")}</div><div class="value">${report.totalBurnedKcal.toLocaleString()} kcal</div></div>
    <div class="card"><div class="label">${summaryLabel("Food consumed", "Total consumed")}</div><div class="value">${report.totalConsumedKcal.toLocaleString()} kcal</div></div>
    <div class="card"><div class="label">${summaryLabel("Water intake", "Total water")}</div><div class="value">${report.waterMl.toLocaleString()} ml</div></div>
    <div class="card"><div class="label">${summaryLabel("Steps", "Total steps")}</div><div class="value">${report.steps.toLocaleString()}</div></div>
    <div class="card"><div class="label">Weight</div><div class="value">${report.weightKg != null ? `${report.weightKg.toFixed(1)} kg` : "—"}</div></div>
    <div class="card"><div class="label">Workouts completed</div><div class="value">${report.workouts.length}</div></div>
  </div>

  ${listSection("Workouts", workoutRows, "No workouts completed in this period.")}
  ${listSection("Nutrition", mealRows, "No meals logged in this period.")}
  ${listSection("Water intake", waterRows, "No water logged in this period.")}
  ${listSection("Steps", stepRows, "No steps recorded in this period.")}
  ${listSection("Weight", weightRows, report.weightKg != null ? `Latest weight: ${report.weightKg.toFixed(1)} kg` : "No weight logged in this period.")}
  ${listSection("Achievements unlocked", achievementRows, "No achievements unlocked in this period.")}

  <p class="footer">Generated by Personalised Workout and Nutrition Guidance Application</p>
</body>
</html>`;
}

export async function shareUserReportPdf(report: UserReport): Promise<void> {
  const html = buildUserReportHtml(report);
  const { uri } = await Print.printToFileAsync({
    html,
    base64: false,
  });

  const canShare = await Sharing.isAvailableAsync();
  if (!canShare) {
    throw new Error("Sharing is not available on this device.");
  }

  const fileName = reportFileName(report);
  const pdf = new File(uri);
  const existing = new File(pdf.parentDirectory, fileName);
  if (existing.exists) {
    existing.delete();
  }
  pdf.rename(fileName);

  // Expo Sharing only accepts file:// URLs. Preferring File.contentUri on Android
  // caused: "expected scheme to be 'file', got 'content'".
  const shareUri = pdf.uri.startsWith("file") ? pdf.uri : uri;
  if (!String(shareUri).startsWith("file")) {
    throw new Error("Could not prepare a local PDF file for sharing.");
  }

  await Sharing.shareAsync(shareUri, {
    mimeType: "application/pdf",
    UTI: "com.adobe.pdf",
    dialogTitle: reportShareTitle(report),
  });
}
