# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18kI4tFnT-dcqnfAEu8CIagZKZBqnILcz
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import joblib

from sklearn.model_selection import (
    train_test_split,
    KFold,
    cross_validate
)
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import (
    r2_score,
    mean_absolute_error,
    mean_squared_error
)


# =========================================================
# 1. Load dataset
# =========================================================

df = pd.read_csv("advanced_water_dataset.csv")

print("Dataset shape:", df.shape)
print("\nMissing values:")
print(df.isnull().sum())


# =========================================================
# 2. Define input features and target variable
# =========================================================

feature_columns = [
    "age",
    "weight",
    "height",
    "gender",
    "BMI",
    "temperature",
    "humidity",
    "weather_condition",
    "altitude",
    "activity_level",
    "activity_duration"
]

target_column = "water_intake"


# Check whether all required columns exist
required_columns = feature_columns + [target_column]

missing_columns = [
    column
    for column in required_columns
    if column not in df.columns
]

if missing_columns:
    raise ValueError(
        f"Missing columns in dataset: {missing_columns}"
    )


X = df[feature_columns].copy()
y = df[target_column].copy()


# =========================================================
# 3. Separate numerical and categorical features
# =========================================================

numerical_features = [
    "age",
    "weight",
    "height",
    "BMI",
    "temperature",
    "humidity",
    "altitude",
    "activity_duration"
]

categorical_features = [
    "gender",
    "weather_condition",
    "activity_level"
]


# =========================================================
# 4. Data preprocessing
# =========================================================

# Fill missing numerical values using median
numerical_pipeline = Pipeline(
    steps=[
        (
            "imputer",
            SimpleImputer(strategy="median")
        )
    ]
)


# Fill missing categorical values and apply one-hot encoding
categorical_pipeline = Pipeline(
    steps=[
        (
            "imputer",
            SimpleImputer(strategy="most_frequent")
        ),
        (
            "onehot",
            OneHotEncoder(
                handle_unknown="ignore",
                sparse_output=False
            )
        )
    ]
)


preprocessor = ColumnTransformer(
    transformers=[
        (
            "numerical",
            numerical_pipeline,
            numerical_features
        ),
        (
            "categorical",
            categorical_pipeline,
            categorical_features
        )
    ]
)


# =========================================================
# 5. Divide dataset into training and testing sets
# =========================================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

print("\nTraining records:", len(X_train))
print("Testing records:", len(X_test))


# =========================================================
# 6. Define Gradient Boosting Regression model
# =========================================================

gradient_boosting_model = GradientBoostingRegressor(
    n_estimators=150,
    learning_rate=0.05,
    max_depth=3,
    min_samples_split=2,
    min_samples_leaf=1,
    subsample=1.0,
    random_state=42
)


# Combine preprocessing and model in one pipeline
model_pipeline = Pipeline(
    steps=[
        (
            "preprocessor",
            preprocessor
        ),
        (
            "model",
            gradient_boosting_model
        )
    ]
)


# =========================================================
# 7. Perform 5-fold cross-validation
# =========================================================

five_fold_cv = KFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)


scoring_metrics = {
    "r2": "r2",
    "mae": "neg_mean_absolute_error",
    "rmse": "neg_root_mean_squared_error"
}


# Cross-validation is performed only on training data
cv_results = cross_validate(
    estimator=model_pipeline,
    X=X_train,
    y=y_train,
    cv=five_fold_cv,
    scoring=scoring_metrics,
    n_jobs=-1,
    return_train_score=False
)


# Obtain scores from each fold
cv_r2_scores = cv_results["test_r2"]

# Convert negative error scores into positive values
cv_mae_scores = -cv_results["test_mae"]
cv_rmse_scores = -cv_results["test_rmse"]


# =========================================================
# 8. Train model using the complete training dataset
# =========================================================

model_pipeline.fit(X_train, y_train)


# =========================================================
# 9. Generate predictions
# =========================================================

training_predictions = model_pipeline.predict(X_train)
testing_predictions = model_pipeline.predict(X_test)


# =========================================================
# 10. Calculate training and testing metrics
# =========================================================

training_r2 = r2_score(
    y_train,
    training_predictions
)

testing_r2 = r2_score(
    y_test,
    testing_predictions
)

test_mae = mean_absolute_error(
    y_test,
    testing_predictions
)

test_rmse = np.sqrt(
    mean_squared_error(
        y_test,
        testing_predictions
    )
)

r2_gap = training_r2 - testing_r2


# =========================================================
# 11. Display evaluation results
# =========================================================

print("\n" + "=" * 60)
print("GRADIENT BOOSTING REGRESSION RESULTS")
print("=" * 60)

print(f"Training R²:             {training_r2:.6f}")
print(f"Testing R²:              {testing_r2:.6f}")
print(f"Training–Testing R² Gap: {r2_gap:.6f}")
print(f"Test MAE:                {test_mae:.6f}")
print(f"Test RMSE:               {test_rmse:.6f}")


print("\n" + "=" * 60)
print("5-FOLD CROSS-VALIDATION RESULTS")
print("=" * 60)

for fold_number, score in enumerate(
    cv_r2_scores,
    start=1
):
    print(
        f"Fold {fold_number} R²: {score:.6f}"
    )

print(
    f"\n5-Fold CV Mean R²:       "
    f"{cv_r2_scores.mean():.6f}"
)

print(
    f"5-Fold CV R² Std:        "
    f"{cv_r2_scores.std():.6f}"
)

print(
    f"5-Fold CV Mean MAE:      "
    f"{cv_mae_scores.mean():.6f}"
)

print(
    f"5-Fold CV Mean RMSE:     "
    f"{cv_rmse_scores.mean():.6f}"
)


# =========================================================
# 12. Interpret possible overfitting
# =========================================================

print("\n" + "=" * 60)
print("MODEL STABILITY INTERPRETATION")
print("=" * 60)

if r2_gap > 0.10:
    print(
        "The model may be overfitting because the training "
        "R² is considerably higher than the testing R²."
    )

elif r2_gap > 0.05:
    print(
        "The model shows a moderate difference between "
        "training and testing performance."
    )

else:
    print(
        "The training and testing R² scores are reasonably "
        "close. The model does not show strong overfitting."
    )


# =========================================================
# 13. Create results table
# =========================================================

results = pd.DataFrame(
    {
        "Metric": [
            "Training R2",
            "Testing R2",
            "R2 Gap",
            "Test MAE",
            "Test RMSE",
            "5-Fold CV Mean R2",
            "5-Fold CV R2 Standard Deviation",
            "5-Fold CV Mean MAE",
            "5-Fold CV Mean RMSE"
        ],
        "Value": [
            training_r2,
            testing_r2,
            r2_gap,
            test_mae,
            test_rmse,
            cv_r2_scores.mean(),
            cv_r2_scores.std(),
            cv_mae_scores.mean(),
            cv_rmse_scores.mean()
        ]
    }
)

print("\nEvaluation summary:")
print(results.to_string(index=False))


# Save results as CSV
results.to_csv(
    "gradient_boosting_results.csv",
    index=False
)


# =========================================================
# 14. Plot actual values against predicted values
# =========================================================

plt.figure(figsize=(8, 6))

plt.scatter(
    y_test,
    testing_predictions,
    alpha=0.6
)

minimum_value = min(
    y_test.min(),
    testing_predictions.min()
)

maximum_value = max(
    y_test.max(),
    testing_predictions.max()
)

plt.plot(
    [minimum_value, maximum_value],
    [minimum_value, maximum_value],
    linestyle="--"
)

plt.xlabel("Actual Water Intake")
plt.ylabel("Predicted Water Intake")
plt.title(
    "Actual vs Predicted Water Intake\n"
    "Gradient Boosting Regression"
)

plt.tight_layout()

plt.savefig(
    "gradient_boosting_actual_vs_predicted.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()


# =========================================================
# 15. Plot residual distribution
# =========================================================

residuals = y_test - testing_predictions

plt.figure(figsize=(8, 6))

plt.scatter(
    testing_predictions,
    residuals,
    alpha=0.6
)

plt.axhline(
    y=0,
    linestyle="--"
)

plt.xlabel("Predicted Water Intake")
plt.ylabel("Residual")
plt.title(
    "Residual Plot for Gradient Boosting Regression"
)

plt.tight_layout()

plt.savefig(
    "gradient_boosting_residual_plot.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()


# =========================================================
# 16. Save the trained model
# =========================================================

joblib.dump(
    model_pipeline,
    "gradient_boosting_water_intake_model.pkl"
)

print(
    "\nThe trained model was saved as: "
    "gradient_boosting_water_intake_model.pkl"
)

print(
    "The evaluation results were saved as: "
    "gradient_boosting_results.csv"
)